### ISSUE TITLE
Is possible to add these files to the tool

### ISSUE THREAD

**Issue by Mad-Soft** [MikeG621/TieTextEditor#1]
Hi. Happy New Year.
Thanks for you work with this editor.
Would be possible add to the editor to translate, the files: TieText1.lfd, TieText2.lfd, TieText3.lfd and Title.lfd?
I seen with hex editor that they have strings for translate. Even Title.lfd have the strings of typical start of starwars.

Thank a lot

**Comment by MikeG621** [comment]
Yes, I can work on getting those added.
--
Michael Gaisser

**Comment by MikeG621** [comment]
Released
